apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels" . | indent 6 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "common.labels" . | indent 8 }}
  template:
    metadata:
      labels: {{ include "common.labels" . | indent 10 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
